from .generated_ui import Generated
from .InputFrame import Ui_inputFrame
from .MainUI import Ui_MainWindow
from .RamAreaInputed import Ui_RamAreaInput
from .ProcessInput import Ui_ProcessInput
from .DemoFrame import Ui_DemoFrame
from .RamBlockDemo import Ui_RamBlockDemo
from .ProcessDemo import Ui_ProcessDemo
from .ProcessOVEntry import Ui_ProcessOVEntry
