# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Workspace\NTU_project\ThucTapCoSo\Simulating RAM MAP\Views\ProcessDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessDemo(object):
    def setupUi(self, ProcessDemo):
        ProcessDemo.setObjectName("ProcessDemo")
        ProcessDemo.resize(508, 120)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ProcessDemo)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainBodyContainer = QtWidgets.QWidget(ProcessDemo)
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainBodyContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.index_lb = QtWidgets.QLabel(self.mainBodyContainer)
        self.index_lb.setMinimumSize(QtCore.QSize(50, 0))
        self.index_lb.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.index_lb.setFont(font)
        self.index_lb.setText("")
        self.index_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.index_lb.setObjectName("index_lb")
        self.horizontalLayout_2.addWidget(self.index_lb)
        self.capacity_lb = QtWidgets.QLabel(self.mainBodyContainer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.capacity_lb.setFont(font)
        self.capacity_lb.setText("")
        self.capacity_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.capacity_lb.setObjectName("capacity_lb")
        self.horizontalLayout_2.addWidget(self.capacity_lb)
        self.horizontalLayout.addWidget(self.mainBodyContainer)

        self.retranslateUi(ProcessDemo)
        QtCore.QMetaObject.connectSlotsByName(ProcessDemo)

    def retranslateUi(self, ProcessDemo):
        _translate = QtCore.QCoreApplication.translate
        ProcessDemo.setWindowTitle(_translate("ProcessDemo", "Form"))
