# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Workspace\NTU_project\ThucTapCoSo\Simulating RAM MAP\Views\ProcessOVEntry.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessOVEntry(object):
    def setupUi(self, ProcessOVEntry):
        ProcessOVEntry.setObjectName("ProcessOVEntry")
        ProcessOVEntry.resize(797, 40)
        ProcessOVEntry.setMinimumSize(QtCore.QSize(0, 30))
        ProcessOVEntry.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalLayout = QtWidgets.QHBoxLayout(ProcessOVEntry)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(ProcessOVEntry)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(12, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.processNo_lb = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.processNo_lb.setFont(font)
        self.processNo_lb.setObjectName("processNo_lb")
        self.horizontalLayout_4.addWidget(self.processNo_lb)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.processSize_lb = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.processSize_lb.setFont(font)
        self.processSize_lb.setObjectName("processSize_lb")
        self.horizontalLayout_3.addWidget(self.processSize_lb)
        self.horizontalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.blockNo_lb = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.blockNo_lb.setFont(font)
        self.blockNo_lb.setObjectName("blockNo_lb")
        self.horizontalLayout_5.addWidget(self.blockNo_lb)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(ProcessOVEntry)
        QtCore.QMetaObject.connectSlotsByName(ProcessOVEntry)

    def retranslateUi(self, ProcessOVEntry):
        _translate = QtCore.QCoreApplication.translate
        ProcessOVEntry.setWindowTitle(_translate("ProcessOVEntry", "Form"))
        self.processNo_lb.setText(_translate("ProcessOVEntry", "TextLabel"))
        self.processSize_lb.setText(_translate("ProcessOVEntry", "TextLabel"))
        self.blockNo_lb.setText(_translate("ProcessOVEntry", "TextLabel"))
