# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Workspace\NTU_project\ThucTapCoSo\Simulating RAM MAP\Views\ProcessInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessInput(object):
    def setupUi(self, ProcessInput):
        ProcessInput.setObjectName("ProcessInput")
        ProcessInput.resize(453, 50)
        ProcessInput.setMinimumSize(QtCore.QSize(0, 30))
        ProcessInput.setMaximumSize(QtCore.QSize(16777215, 50))
        ProcessInput.setStyleSheet("\n"
".QPushButton {\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"#bodyContainer {\n"
"    background-color: #485ECE;\n"
"}\n"
"\n"
"#index_lb {\n"
"    color: #000;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcessInput)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bodyContainer = QtWidgets.QWidget(ProcessInput)
        self.bodyContainer.setObjectName("bodyContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bodyContainer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.bodyContainer)
        self.frame_2.setMinimumSize(QtCore.QSize(32, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(36, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.up_btn = QtWidgets.QPushButton(self.frame_2)
        self.up_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/direction.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_btn.setIcon(icon)
        self.up_btn.setObjectName("up_btn")
        self.verticalLayout_2.addWidget(self.up_btn)
        self.down_btn = QtWidgets.QPushButton(self.frame_2)
        self.down_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_btn.setIcon(icon1)
        self.down_btn.setObjectName("down_btn")
        self.verticalLayout_2.addWidget(self.down_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.bodyContainer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.index_lb = QtWidgets.QLabel(self.frame)
        self.index_lb.setMinimumSize(QtCore.QSize(30, 0))
        self.index_lb.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.index_lb.setFont(font)
        self.index_lb.setText("")
        self.index_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.index_lb.setObjectName("index_lb")
        self.horizontalLayout_3.addWidget(self.index_lb)
        self.capacity_lb = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.capacity_lb.setFont(font)
        self.capacity_lb.setText("")
        self.capacity_lb.setObjectName("capacity_lb")
        self.horizontalLayout_3.addWidget(self.capacity_lb)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.bodyContainer)
        self.frame_3.setMinimumSize(QtCore.QSize(32, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(32, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.del_btn = QtWidgets.QPushButton(self.frame_3)
        self.del_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon2)
        self.del_btn.setIconSize(QtCore.QSize(16, 16))
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_2.addWidget(self.del_btn)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.bodyContainer)

        self.retranslateUi(ProcessInput)
        QtCore.QMetaObject.connectSlotsByName(ProcessInput)

    def retranslateUi(self, ProcessInput):
        _translate = QtCore.QCoreApplication.translate
        ProcessInput.setWindowTitle(_translate("ProcessInput", "Form"))
from Views import resourse_rc
