# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Workspace\NTU_project\ThucTapCoSo\Simulating RAM MAP\Views\RamAreaInputed.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RamAreaInput(object):
    def setupUi(self, RamAreaInput):
        RamAreaInput.setObjectName("RamAreaInput")
        RamAreaInput.resize(352, 40)
        RamAreaInput.setMinimumSize(QtCore.QSize(0, 40))
        RamAreaInput.setMaximumSize(QtCore.QSize(16777215, 100))
        RamAreaInput.setStyleSheet("* {\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"#capacity_le {\n"
"    background-color: rgba(255,255,255,0);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(RamAreaInput)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bodyContainer = QtWidgets.QWidget(RamAreaInput)
        self.bodyContainer.setObjectName("bodyContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bodyContainer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.bodyContainer)
        self.frame.setMinimumSize(QtCore.QSize(32, 0))
        self.frame.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.up_btn = QtWidgets.QPushButton(self.frame)
        self.up_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/direction.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_btn.setIcon(icon)
        self.up_btn.setObjectName("up_btn")
        self.verticalLayout_3.addWidget(self.up_btn)
        self.down_btn = QtWidgets.QPushButton(self.frame)
        self.down_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_btn.setIcon(icon1)
        self.down_btn.setObjectName("down_btn")
        self.verticalLayout_3.addWidget(self.down_btn)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.bodyContainer)
        self.frame_2.setMinimumSize(QtCore.QSize(130, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.capacity_lb = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.capacity_lb.setFont(font)
        self.capacity_lb.setText("")
        self.capacity_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.capacity_lb.setObjectName("capacity_lb")
        self.verticalLayout_2.addWidget(self.capacity_lb)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.bodyContainer)
        self.frame_3.setMinimumSize(QtCore.QSize(32, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.del_btn = QtWidgets.QPushButton(self.frame_3)
        self.del_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon2)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_2.addWidget(self.del_btn)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.bodyContainer)

        self.retranslateUi(RamAreaInput)
        QtCore.QMetaObject.connectSlotsByName(RamAreaInput)

    def retranslateUi(self, RamAreaInput):
        _translate = QtCore.QCoreApplication.translate
        RamAreaInput.setWindowTitle(_translate("RamAreaInput", "Form"))
from Views import resourse_rc
